with
    mart as (select * from {{ ref("dim_organisation") }}),

    renamed as (

        select
            organisation_date_sk,
            organisation_hk,
            report_date,
            organisation_id,
            organisation_name,
            email_domain_name,
            generic_domain_flag,
            email_address_description,
            create_date,
            edapp_org_id,
            industry_type_description,
            industry_sub_type_description,
            industry_sector_type_description,
            employee_count_band_description,
            number_of_employees,
            mqa_score_number,
            total_seat_count_buckets,
            account_billing_street,
            account_billing_city,
            account_billing_state,
            account_billing_country,
            account_billing_postal_code,
            billing_country_name,
            billing_address,
            billing_city_name,
            billing_country_code,
            billing_state_code,
            billing_zip_code,
            customer_billing_country_name,
            owner_relationship_description,
            owner_relationship_subtype_description,
            sales_managed_flag,
            team_id,
            account_id,
            account_name,
            parent_account_id,
            parent_account_name,
            account_rd_domain_description,
            account_segment_description,
            msa_team_flag,
            derived_billing_email_address_description,
            account_owner_id,
            account_owner_name,
            account_owner_role,
            account_owner_sub_role,
            account_owner_region_code,
            account_owner_sub_region_code,
            account_owner_email,
            account_owner_manager_name,
            success_managed_flag,
            customer_success_manager_id,
            customer_success_manager_name,
            customer_success_manager_role,
            customer_success_manager_sub_role,
            customer_success_manager_region_code,
            customer_success_manager_sub_region_code,
            customer_success_manager_email,
            csm_owner_manager_name,
            customer_onboarding_manager_id,
            customer_onboarding_manager_name,
            customer_onboarding_manager_role,
            customer_onboarding_manager_sub_role,
            customer_onboarding_manager_region_code,
            customer_onboarding_manager_sub_region_code,
            customer_onboarding_manager_email,
            com_owner_manager_name,
            nurture_comms_opt_in_flag,
            price_change_auto_uplift_flag,
            price_change_send_marketing_flag,
            finance_reason_for_not_auto_uplifting_flag,
            gtm_reason_for_not_auto_uplifting_flag,
            renewal_comms_opt_out_date,
            derived_country_name,
            derived_region_group,
            derived_region_code,
            derived_sub_region_code,
            sites_enabled_flag,
            onboarding_flag,
            within_onboarding_flag,
            tech_touch_onboard_start_date,
            exclude_from_analytics_flag,
            test_account_flag,
            latest_date_flag

        from mart

    )

select *
from renamed
